---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  namespace: csi-driver-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.1.254"
  share: /mnt/disk1/kubernetes
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
allowVolumeExpansion: true
