---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  namespace: csi-driver-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: "${SECRET_NFS_ADDR}"
  share: /mnt/disk1/kubernetes
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
allowVolumeExpansion: true
