---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: bookmarks
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.pascaliske.dev
      chart: linkding
      version: 0.0.2
      sourceRef:
        kind: HelmRepository
        name: linkding-charts
        namespace: flux-system
  values:
    podSecurityContext:
      supplementalGroups:
        - 65534
    # podSecurityContext:
    #   runAsUser: 65534
    #   runAsGroup: 65534
    #   fsGroup: 65534
    #   fsGroupChangePolicy: OnRootMismatch
    image:
      repository: sissbruecker/linkding
      tag: 1.8.8
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
          #hajimari.io/enable: "true"
          #hajimari.io/icon: shield-lock
        hosts:
          - host: &host links.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: linkding-tls
    persistence:
      config:
        enabled: true
        existingClaim: linkding-config
