---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podSecurityContext:
      supplementalGroups:
        - 65534
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1802
    env:
      TZ: "America/Los_Angeles"
    podAnnotations:
      setGateway: "true"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "prowlarr.${SECRET_DOMAIN}"
            secretName: prowlarr-tls
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
      shared:
        enabled: true
        emptyDir:
          enabled: true
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1000Mi
