---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    podSecurityContext:
      supplementalGroups:
        - 65534
    # podSecurityContext:
    #   runAsUser: 65534
    #   runAsGroup: 65534
    #   fsGroup: 65534
    #   fsGroupChangePolicy: OnRootMismatch
    image:
      repository: vaultwarden/server
      tag: 1.24.0
    env:
      DOMAIN: https://vault.${SECRET_DOMAIN}
      #DATABASE_URL: postgresql://vaultwarden:${VAULTWARDEN_POSTGRES_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden
      #ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SIGNUPS_ALLOWED: false
      #YUBICO_CLIENT_ID: ${VAULTWARDEN_YUBICO_CLIENT_ID}
      #YUBICO_SECRET_KEY: ${VAULTWARDEN_YUBICO_SECRET_KEY}
      WEBSOCKET_ENABLED: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: shield-lock
        hosts:
          - host: &host vault.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: vaultwarden-tls
      # admin:
      #   enabled: true
      #   annotations:
      #     external-dns.alpha.kubernetes.io/target: ${DOMAIN}
      #     cert-manager.io/cluster-issuer: letsencrypt-production
      #     nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
      #     traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      #     traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
      #   hosts:
      #     - host: *host
      #       paths:
      #         - path: /admin
      #           pathType: Prefix
      #   tls:
      #     - hosts:
      #         - *host
      #       secretName: vaultwarden-tls
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
#    persistence:
#      config:
#        enabled: true
#        type: emptyDir
#        mountPath: /config
    # postgresql:
    #   enabled: true
    #   postgresqlUsername: vaultwarden
    #   postgresqlPassword: ${VAULTWARDEN_POSTGRES_PASSWORD}
    #   postgresqlDatabase: vaultwarden
    #   persistence:
    #     enabled: true
    #     existingClaim: vaultwarden-postgresql
