# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:NcuN6H+Wf7e3R8h4DVGPOg==,iv:BzLgt0P2PKP7VI4MmV+2OQW1myNPQsGcZ1CpIs7odqo=,tag:IQsviun30QMqDCxzO8UMLg==,type:str]
    api-key: ENC[AES256_GCM,data:Dz6Qr4EJi0NcU58strE96VIsWLqM3SoGp5z3LkJ6jjuY9TSMUw==,iv:kuWtMaEe7TjHK/If2tH1Laiw0wLi9hsYC5RSknTdB08=,tag:nkDMDM5m58Mr4KykepeYew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlYrMld3MkdmYWtLaWtM
            cXM2cGdhRklTd3dIZXJuMVIrNExmYVBuTUVJCmYvSlkxUkRpUTdwL2ZmSUJxTEgz
            bVc2WElYbWhSNldOZERvbVBUR2JEcVkKLS0tIGVmVGJJbVFCMWVpVjlFcVR4aEtS
            ZWRHd2xFaFlyZ3V2QzY5bVQ2SHY3UU0KpWrdGOyhUil3+lBk9SP4jkXTf/AdZ34v
            3wJ+eZ5tjvnMsT0iyCX8pxhbGhLleHUtw56u8c3EzkQNoXr9/fZe7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T19:51:41Z"
    mac: ENC[AES256_GCM,data:BUhCaiOV6q71pKKlkTRBY5El6u83AQnBbh1m0VvaM8m3gEtATZsYBB9neivdTiR/fZU/rlMZeYePOTu31rb89g40UZwfUropEFfTshhRSfXclsSplvVYbyYAiRLiq4YmSEFKxV2fGHdRiJFKVY7jw6wznNqv1l0UnJeaRYDic58=,iv:Y2z4lg+Tlx4shkJjd8U3LKVBrsiUrGFnd/F4hTWlcnY=,tag:dDci+NXFdszK0hi7bWurcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
