---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.1.150-192.168.1.160
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.150
  METALLB_TRAEFIK_ADDR: 192.168.1.151
