---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nfs-pv
  namespace: downloads
spec:
  storageClassName: downloads-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.25
    path: "/local-zfs/media/downloads"
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: downloads
spec:
  storageClassName: downloads-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
