---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-downloads-pv
  namespace: downloads
spec:
  storageClassName: media-nfs-downloads
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.25
    path: "/local-zfs/media"
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-pvc
  namespace: downloads
spec:
  storageClassName: media-nfs-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
