---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-config
  namespace: bookmarks
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
