---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-v1
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
