apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-vpnconfig
    namespace: downloads
type: Opaque
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:6l7r7vbqDJzeS2y2L1gisRG89/wtY0GRuJVv3hYY8GOdkviv6DchMq4EB2qnCOTTXYPkq+Pt6EyDQKMGWporR3fi+KpFHhS7li30v+DPjxcmz2g/RZ0aBuJIKCHf0grWMTK/R2A1v0/UaAWhYbAx3CyOILRFE1n4c6iQNXcc6OMLIi9Vu6/M2EamXQP1obdhCAl4Ttka47qD8wjpJ/u5LUkBZh5tQ74LClQ/qyQ16/9pn5H4TsRtll5nwIBAbUn92ElSwXB4U6t01b6g0ZScogATcS14q8T0TVeprN7m4W9f+e7n/J3JtwY+k1LUaBsEwPRHyWE3KQBvq2tJF/+pwV/22cw4P9ZbBZjaEg==,iv:XR1KiJIGYmTDJZptLK1ogTXt75lNv+jXyg4jLkyROTY=,tag:s2qMrYon3/n7OKzai6uhMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZWRadXVMRUF5WmVuMlpp
            T2Z5VCtlMXJZT0xFcDVOcWkxSFduUDZHSGt3Clgyd1ZoMlBKS2pTMXl5Sm9BdFU4
            NXA2VHNpbGY5aWNCbEIxTTc3U3BuYzQKLS0tIFhhQmc5QW8wQWRuWlgzTStWWXBR
            S3dodXovTmpYeEs5eUlxOWcwLzRKNzAKlpOTM0jqvZokDa6LVCSd2uqdqZVkS59O
            ToWpajblsk3KZ+IfwPJF7i5O1hrVlI9Q/4aZLb4aDmYY7yAe7A7hAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T04:33:14Z"
    mac: ENC[AES256_GCM,data:dB3pBjYm85o+zSXPnYk5PMFZ2DVOrBWiYfRY+jxfcRfABpSXBK6TaXgJhIW42ZkHPEHrL08elowf16MM4Xl7JFU2jEo3WYKzBivimjTDC5nIaNt7ln2Unzzx8tfAcR6zKl3J/WNE0scGftFxv6j5wDMP4w+j/pqWGwbplyYRDTc=,iv:Co2yC8b9SvqHpbvyPu88aSoyWfhbVvfNX5kQTKIH0SI=,tag:YWt7jGQ7f5jDAi/l52ZNSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
