# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ivE+C0GbaA7Hwg9286znydFq3TM6BIrZgCD1aYHXUySp7iZx6FPzGA==,iv:LwBSdS3ueNEL68AiD30N5zHVKlX8mS1q/S21QhH3MxQ=,tag:QxlyqheFPEKDT/L6ufewiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRkQzVGJqdXVtQXYvbHdX
            VFhGdDE2NDYwd2phVnVBOXpZb0dGdVdKUDJBCloraEFraUNJbC9ucGx5TmowM3VU
            dEkxdXFPSkJaZFk4ajZaWnRuV1lUL1EKLS0tIFpDSngwVXRMd0EvOFFzQmhpRHEr
            UmlKeWwvSnpJaWhScGlDSm00MUZaWkEK05bAR4UHiIRfMwrBHgb0fe8pTWKK3uJ/
            CZx6Ju6j+BHhSVuPazuYlZ9OmtukOSp4jrziPBRpGUkrA9/SQIWhAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-20T17:47:26Z"
    mac: ENC[AES256_GCM,data:r/NdnDIBJfXzv9VZiIC+Bjcn1+j1Qbptbn6K06huKMilMCEQSHDSAa26Jc6s1zSTmVn2Z3tY0Mgq5HkA3bCAjb5I0AMH7qG3/d/y9Vy3haOXBGxWAHJ4uTsACW8XRg5+xJG2gNH47WeVC9jno3vXTDXxbL1I7nHehyZGWWyWKoc=,iv:xEBP/TQeCisBXuNLG0jIwpV787Hkkq1s5HkLddFKbjc=,tag:+bhy32brPgzi9YL19UIzwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
