# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:CORQ3Vj1ndqkcR1a3R2W2MvKkLsY7uelozc3k2V/FvD95MjY4w==,iv:KQSfrU9F7a7GSPLIi11fRhkn3d+cEGktP5/PFU9iU2c=,tag:IOVhPsK5tlZ8o7TtK0cI1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NUxCaDRjeW5vN0FzY3dr
            aVpYekZjN1RNV2FOdE12Vml6VUFnQTlwNkRRCk1yK0dVT2NjTFFYNVdpREFReEJX
            UTYvSEw2Q1VhQ2dXUU1yNXdxamptdEEKLS0tIDNwUWlsa2c5T0g1d3lYb3cxbE9s
            SmF5amxsTjlZVk9idlRxNGJudGNuUncKS0hZ1wV27JZ+VRgDrU4IzDxmF+zGwc/1
            WBOM11VD6sxT9DEFHQpXdLZjTiwqE6Bjjpj8POX8/kam8b8w4bBq3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T19:51:41Z"
    mac: ENC[AES256_GCM,data:ZEVeuWY/Pz/VYj3SSzOxLZ+6eXicyhvK3HIgSmvYLsJQpXhMSqr3KHM8AXPQLtvu6HhKlPLJ1B5QiUQ6/jClKmzxAoxKPhVkXT2pDu8dfD8EPHnMKkem2KmW6rWxNdT2BY8FlujhV/rOtqaI3xih+eXM6lSQsAygJyIpXCgN1NI=,iv:pAAooRsHEyGhGzgE7otk6tCLbUff4sl3BHW27N1tc5g=,tag:pAntAgINzeBg18cdk6Dd2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
