---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-v1
  namespace: passwords
spec:
  accessModes:
    - ReadWrite
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
